### ISSUE TITLE
Better log streaming solution

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#52]
When streaming logs via `curl`, it seems to disconnect after a minute or so. I'm not sure exactly where this issue originates (Docker API/Gin/nginx), but I'll find out 🔎

This is the error:
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by jasonappah** [comment]
Closing because (I think?) this has been solved. See https://hackclub.slack.com/archives/C01N3B30TFB/p1619551926027200 for context

**Comment by anirudhb** [comment]
Not solved. That's a temporary solution and doesn't scale... which is why WebSockets or SSE should be considered instead.
